name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decompress GZip file
        run: |
          gzip -d satnotcanvas/godotapk/Exportgodotlab.wasm.gz

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: satnotcanvas/godotapk

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
