name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Decompress .wasm file
        run: |
          gzip -d wasm1/exportgodotlab.wasm.gz

      - name: Checkout satnotcanvas2 branch (pck file)
        uses: actions/checkout@v4
        with:
          ref: satnotcanvas2
          path: satnotcanvas2

      - name: Move .pck file to target directory
        run: |
          mv satnotcanvas2/godotapk/exportgodotlab.pck godotapk/exportgodotlab.pck

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # Upload the root content after merging both files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
